before_install:
  - git clone --quiet --depth 1 --single-branch https://github.com/vim/vim.git /tmp/vim
  - cd /tmp/vim
  - ./configure --prefix=$PWD/build --with-features=huge
  - make -j2
  - make install
  - export PATH=$PWD/build/bin:$PATH
  - cd -

  - git clone https://github.com/thinca/vim-themis --quiet --branch v1.5.3 --single-branch --depth 1 /tmp/vim-themis

before_script:
  - vim --version

script:
  - /tmp/vim-themis/bin/themis --reporter dot
